# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: backupctl

before:
  hooks:
    - sh -c 'go test $(go list ./... | grep -v "/internal/integration$")'

builds:
  - id: backupctl
    main: ./cmd/backupctl
    binary: backupctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/valpiks/backupctl/internal/app.Version={{ .Version }}

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
